# By submitting this assignment, I agree to the following:
#   "Aggies do not lie, cheat, or steal, or tolerate those who do."
#   "I have not given or received any unauthorized aid on this assignment."
#
# Names:        Sanjay Gopi
#               Emmanuelle Chern
# Section:      218
# Assignment:   Mini Project 3 L3
# Date:         1 October 2026

days = [
    # Day 1 -- 50 records
    'DFWIAHDELPDFWMELPCLLWDFWELPMDFWIAHBCLLELPPIAHDFWWELPCLLMDFWELPMSATELPMIAHDFWGAUSIAHMSATELPMELPSATMELPAUSWIAHSATPCLLAUSMSATDFWPAUSSATBELPCLLPIAHELPPAUSSATBSATDFWDSATCLLMSATDFWMCLLDFWPDFWSATWIAHELPWSATELPPAUSELPBCLLELPWSATELPWDFWELPWCLLDFWPSATIAHPAUSELPGCLLELPCELPCLLCSATIAHBELPCLLPCLLDFWMDFWSATCELPCLLPELPDFWMDFWCLLMSATCLLMAUSCLLMSATDFWCDFWELPPCLLELPM',
    # Day 2 -- 70 records
    'DFWAUSMIAHELPCDFWSATWCLLSATBAUSCLLWCLLDFWWAUSDFWBELPAUSPAUSSATBIAHCLLBSATIAHDIAHAUSMDFWAUSMDFWSATMSATAUSPSATDFWGELPAUSPDFWSATDCLLAUSCAUSIAHPSATDFWMDFWSATBCLLSATWDFWSATMCLLDFWWDFWAUSWCLLDFWDCLLDFWGCLLDFWWDFWSATCAUSIAHMIAHCLLWCLLSATPSATCLLCDFWAUSMCLLSATPAUSIAHPSATAUSPELPCLLMELPSATMAUSSATPCLLDFWBCLLDFWBSATDFWDDFWAUSPAUSDFWMIAHELPMELPAUSPAUSELPMCLLDFWWIAHAUSWDFWIAHGCLLELPCIAHSATPAUSCLLMCLLSATGCLLDFWCDFWIAHBSATIAHMDFWIAHWIAHCLLDDFWSATWSATDFWWDFWSATMIAHELPMIAHELPMELPDFWMAUSDFWWSATAUSWCLLDFWM',
    # Day 3 -- 230 records
    'DFWIAHWDFWELPWSATIAHWSATIAHWAUSIAHWDFWSATDDFWCLLWAUSIAHPIAHCLLPELPSATDSATDFWDCLLDFWWIAHDFWWAUSELPWSATDFWWSATCLLWELPDFWWIAHSATCCLLELPDIAHAUSGSATELPWDFWSATWDFWAUSPCLLELPCAUSCLLWCLLELPWELPDFWWCLLIAHCELPSATGDFWELPGIAHAUSWDFWELPGCLLIAHWELPSATGAUSSATGCLLSATMIAHCLLCAUSIAHMAUSSATWAUSELPWELPCLLCIAHCLLDIAHSATMIAHELPWIAHCLLCCLLAUSCAUSDFWDAUSELPWAUSDFWWSATCLLWSATDFWWELPIAHWSATAUSPCLLSATGELPIAHBELPIAHWCLLAUSWELPAUSWELPAUSCSATCLLWDFWCLLWIAHDFWBELPSATWCLLDFWCDFWAUSDSATCLLGDFWCLLWDFWCLLCCLLIAHWCLLDFWWDFWIAHWCLLSATMDFWAUSCDFWAUSWELPIAHCELPAUSMDFWSATWSATIAHWIAHELPMIAHCLLDCLLDFWWCLLELPDDFWELPWAUSIAHWSATAUSWDFWCLLWSATAUSGIAHDFWWDFWIAHWSATCLLCCLLAUSWIAHCLLWAUSIAHGIAHAUSDSATIAHWDFWELPMELPIAHWCLLSATWELPIAHMDFWELPBIAHDFWGAUSIAHWDFWELPWELPCLLWELPSATGIAHAUSWSATAUSWCLLELPDDFWSATCCLLELPDCLLIAHCDFWAUSCDFWSATWCLLIAHCAUSELPWAUSDFWCAUSIAHCDFWIAHWIAHCLLDIAHSATWIAHELPMAUSSATWSATELPMIAHCLLDCLLSATWDFWELPGELPIAHWSATELPBDFWIAHWDFWELPCSATDFWMIAHCLLGDFWCLLWSATDFWCELPSATGSATDFWCCLLSATWAUSELPWELPCLLWAUSCLLGCLLSATMDFWIAHWIAHCLLWCLLAUSWELPSATMAUSCLLWAUSDFWCAUSSATWSATELPDAUSDFWMELPSATWELPDFWMCLLELPWDFWCLLCCLLAUSCDFWSATCELPDFWBELPSATWIAHELPWELPSATWCLLSATWIAHELPWSATDFWMCLLAUSWCLLAUSMELPDFWWAUSCLLWSATELPGELPIAHWDFWIAHMDFWAUSWSATDFWWAUSCLLCSATDFWDSATDFWDELPSATMELPAUSWCLLSATWAUSSATMIAHDFWCCLLDFWWCLLAUSDELPAUSWAUSSATWDFWCLLWCLLIAHMSATDFWSIAHDFWDAUSDFWWAUSCLLPSATCLLWDFWSATWDFWCLLWELPDFWDCLLDFWCSATDFWGCLLELPWAUSELPCSATDFWCELPCLLWCLLIAHCSATELPMIAHDFWWELPAUSWSATDFWMIAHSATMIAHELPWELPSATWCLLAUSPSATCLLCELPAUSWCLLIAHGIAHAUSBCLLSATCSATELPDIAHSATWSATIAHWIAHCLLGAUSELPPSATCLLWDFWELPMIAHSATWSATIAHWIAHELPWIAHSATDSATAUSWCLLSATCIAHELPPDFWELPWELPDFWW',
    # Day 4 -- 284 records
    'SATIAHCCLLAUSGELPDFWBCLLDFWMSATDFWWCLLELPDSATIAHDDFWELPSAUSSATGSATIAHGAUSIAHWIAHAUSWAUSCLLCCLLSATPCLLAUSGIAHSATCDFWCLLWAUSDFWWSATIAHMELPAUSMAUSELPMCLLDFWWDFWAUSMCLLIAHWSATIAHGAUSSATDELPCLLMELPSATCAUSIAHCSATCLLWELPDFWDSATAUSCAUSELPWELPCLLMIAHAUSPSATDFWDAUSIAHWDFWIAHCIAHSATGCLLAUSDDFWIAHCCLLAUSCCLLSATWCLLAUSGSATELPWAUSIAHWIAHAUSWAUSIAHWCLLAUSWAUSSATCCLLSATCELPAUSMAUSDFWMELPCLLWCLLDFWMSATCLLWELPDFWWAUSCLLGSATIAHBSATELPWDFWSATCCLLSATGDFWIAHWIAHELPCAUSELPWSATDFWWCLLELPMIAHCLLGAUSDFWWCLLAUSWCLLELPCSATIAHCCLLIAHBSATAUSWAUSELPMELPSATWDFWAUSCSATAUSWELPIAHDIAHSATDIAHDFWCAUSELPWAUSELPWDFWIAHWAUSCLLWSATELPCELPDFWDIAHELPWELPDFWWIAHAUSWCLLAUSDCLLAUSWSATELPWAUSSATWIAHAUSWDFWAUSWAUSCLLGAUSIAHCAUSSATDDFWIAHWSATIAHGELPAUSWELPDFWWELPDFWGIAHCLLDIAHCLLWDFWIAHSELPCLLCDFWELPGSATAUSWELPIAHWAUSELPMCLLELPWAUSCLLDAUSIAHWDFWAUSCSATAUSWSATCLLWCLLAUSCDFWELPWDFWCLLCCLLAUSMDFWELPWAUSIAHDCLLDFWCSATCLLWCLLIAHDAUSCLLWIAHCLLWELPSATGIAHSATCSATAUSCIAHELPGCLLSATCSATELPWCLLSATGELPIAHDSATELPCELPSATWDFWAUSCIAHELPWDFWCLLDAUSCLLWELPSATWAUSCLLWDFWCLLWAUSSATCDFWAUSMSATAUSPSATDFWMDFWSATCAUSSATWDFWELPMAUSDFWMDFWSATCIAHDFWDSATIAHWDFWIAHWAUSCLLWAUSIAHGELPSATWELPCLLWIAHELPCCLLDFWMSATELPWDFWSATMCLLIAHWELPDFWWIAHELPWAUSIAHWCLLIAHBDFWELPGSATCLLMAUSSATWELPCLLWIAHSATWAUSDFWWELPSATCIAHDFWMCLLIAHWDFWSATPCLLSATCCLLDFWGIAHSATDSATCLLMCLLIAHGIAHSATWCLLIAHCSATELPWIAHAUSWCLLIAHWAUSDFWWAUSCLLDCLLDFWGAUSCLLWCLLAUSWCLLELPWAUSDFWCDFWSATPIAHDFWWAUSIAHDELPIAHCIAHCLLCSATIAHCCLLELPGCLLAUSCSATAUSMCLLAUSWAUSSATWSATDFWGSATELPWSATAUSCIAHCLLWAUSDFWWDFWCLLWAUSIAHWIAHCLLDDFWIAHGDFWSATWELPAUSCSATAUSCDFWELPWDFWELPWIAHAUSBIAHAUSCDFWCLLWIAHELPBIAHELPGCLLAUSWDFWSATGCLLIAHWIAHELPWELPSATWSATCLLMELPDFWGDFWELPMELPCLLDELPSATMDFWAUSWAUSDFWCIAHELPWELPIAHCAUSSATWIAHAUSCAUSDFWWCLLDFWDCLLDFWWDFWCLLGSATDFWWSATCLLWAUSELPWIAHSATDELPSATCCLLELPDSATCLLWAUSSATCSATELPCELPCLLWAUSCLLWSATIAHDELPIAHWAUSELPWIAHSATWAUSELPMAUSSATCSATCLLWDFWSATDIAHDFWCIAHSATWCLLIAHWDFWIAHGCLLAUSPAUSELPWIAHAUSWELPIAHWCLLDFWWAUSCLLWDFWAUSWSATIAHCAUSELPGELPSATWAUSSATCAUSIAHGCLLDFWW',
    # Day 5 -- 235 records
    'DFWIAHWCLLIAHWIAHAUSWSATIAHWCLLELPCELPDFWDSATCLLWDFWAUSWELPDFWMAUSSATWSATIAHCSATCLLWDFWIAHCELPAUSWELPCLLDELPCLLDDFWAUSWCLLAUSWCLLAUSPIAHELPWSATIAHWSATAUSGELPAUSGSATIAHBIAHELPWIAHELPWELPDFWGCLLDFWWIAHCLLWDFWAUSMCLLDFWWIAHELPCSATCLLCCLLAUSWCLLSATWELPIAHWSATDFWWSATAUSWDFWCLLGELPDFWSIAHDFWWAUSIAHWSATIAHWIAHDFWMIAHAUSCCLLDFWDAUSCLLWDFWCLLMSATDFWBELPCLLWIAHELPGIAHDFWMDFWELPGSATIAHDDFWAUSWSATELPDSATIAHBAUSIAHMIAHSATCELPAUSWAUSCLLMELPCLLCSATIAHBSATIAHDIAHAUSWCLLAUSWELPSATDDFWSATCELPSATGSATIAHCSATELPMIAHCLLWDFWSATWELPCLLWDFWELPGSATDFWGSATIAHCCLLIAHCAUSDFWGAUSELPCCLLDFWWAUSSATMCLLELPWAUSCLLWIAHSATMELPCLLGSATDFWWDFWIAHWELPDFWDELPAUSCSATELPPAUSELPWIAHSATDELPDFWWAUSCLLWSATIAHGELPCLLWELPDFWWDFWSATGAUSCLLWIAHAUSWCLLELPCIAHCLLGELPAUSWDFWELPCSATELPCDFWIAHWELPCLLCCLLSATWSATIAHGIAHELPGCLLIAHWDFWCLLCDFWELPMELPIAHDELPSATWAUSIAHGAUSELPCELPSATCELPDFWWDFWELPGSATDFWDAUSDFWDIAHCLLPAUSDFWCCLLIAHDELPSATWSATIAHWELPIAHCAUSSATDDFWELPWAUSELPCCLLAUSPELPIAHDDFWIAHCDFWIAHCCLLAUSWAUSIAHCSATCLLCELPIAHMCLLAUSMCLLIAHWDFWAUSWELPCLLDAUSSATWSATAUSWIAHCLLWSATAUSWDFWCLLCAUSCLLWELPSATWSATELPDIAHAUSWDFWSATWAUSCLLWCLLDFWWDFWELPWDFWCLLCELPIAHCDFWCLLDSATELPWAUSIAHCAUSCLLWELPIAHWDFWCLLCDFWCLLWIAHCLLCCLLIAHGCLLAUSWDFWAUSCDFWAUSCDFWELPWCLLIAHMIAHCLLWIAHELPWIAHELPDELPCLLMELPSATWCLLAUSWSATELPBIAHSATMELPAUSCDFWELPWELPAUSWCLLELPCAUSSATWELPAUSWELPDFWCDFWAUSCAUSIAHGAUSCLLCCLLSATWSATCLLMELPAUSWCLLIAHCAUSDFWWDFWIAHWSATIAHCDFWAUSWELPSATMSATDFWWAUSDFWCCLLAUSGIAHELPMAUSDFWWDFWSATGCLLSATDELPCLLWIAHELPWAUSCLLSIAHELPGSATCLLWDFWIAHWELPCLLDELPCLLCSATAUSCAUSELPMDFWIAHGSATIAHCDFWIAHMCLLAUSWCLLAUSWSATAUSWDFWAUSSCLLDFWPDFWAUSCCLLIAHBCLLDFWMELPDFWCAUSSATGCLLAUSGELPCLLBSATAUSCSATIAHWCLLELPW',
    # Day 6 -- 245 records
    'AUSIAHCIAHDFWWIAHCLLWAUSCLLWCLLELPCIAHSATWDFWIAHWAUSCLLWAUSELPDIAHDFWMDFWAUSWIAHSATWCLLELPMCLLSATWAUSDFWWSATELPPCLLSATMSATIAHGSATIAHCDFWCLLWSATAUSWELPIAHWDFWIAHWAUSELPGAUSIAHDSATIAHCAUSSATCSATIAHMSATIAHWIAHSATWSATDFWGIAHCLLWAUSDFWWSATCLLCAUSELPGAUSDFWWIAHELPBELPIAHCIAHAUSCSATAUSCCLLDFWMDFWCLLCAUSELPCIAHDFWBSATDFWWCLLAUSGCLLELPCSATELPWSATELPDAUSDFWWELPDFWDSATELPCDFWSATWELPIAHCCLLSATWIAHCLLMAUSELPSSATDFWWSATAUSWCLLIAHWCLLELPDIAHCLLWDFWCLLWAUSSATWAUSELPWSATCLLWELPDFWWCLLDFWMSATCLLWDFWELPBCLLELPGDFWIAHWCLLDFWWAUSIAHWELPAUSWCLLSATMAUSSATCAUSELPMDFWIAHGIAHDFWCAUSELPWCLLSATCIAHELPMELPAUSDDFWSATGSATDFWCELPDFWWIAHELPWAUSIAHWCLLSATDCLLIAHWSATELPWIAHCLLCIAHELPWIAHAUSMCLLAUSCSATELPWCLLELPSSATIAHCDFWAUSBDFWCLLCDFWAUSGSATIAHCELPAUSGIAHDFWWSATDFWCAUSCLLCIAHDFWCSATAUSCELPCLLMAUSDFWWIAHELPWDFWIAHCIAHDFWMDFWSATCCLLAUSBIAHAUSGIAHCLLWDFWCLLWCLLAUSWELPAUSWAUSSATGSATELPWIAHCLLWCLLAUSWELPCLLCIAHDFWWDFWIAHWDFWSATWAUSDFWMIAHELPCELPSATCELPDFWWSATELPWDFWCLLPIAHAUSGAUSSATCIAHELPMSATELPWDFWCLLMAUSIAHDCLLELPGDFWSATWELPIAHWSATAUSWDFWELPCIAHCLLWELPSATDDFWAUSWSATAUSCCLLIAHCIAHSATDDFWIAHWDFWSATCIAHAUSDAUSELPWELPCLLWSATIAHWDFWSATDSATIAHCSATDFWWSATDFWMIAHCLLWSATAUSWIAHDFWWDFWCLLSAUSDFWCCLLELPMIAHSATWELPCLLCSATIAHWCLLDFWWIAHDFWWCLLIAHCELPIAHWCLLAUSGCLLAUSDSATCLLCSATDFWWAUSIAHWCLLIAHPAUSIAHCCLLELPMSATIAHWSATDFWCDFWAUSCDFWSATWCLLIAHWDFWELPBDFWELPWAUSIAHWAUSDFWPCLLSATGAUSIAHWDFWCLLWIAHAUSWSATDFWCCLLSATDDFWCLLCCLLDFWWDFWCLLWCLLSATGCLLSATSDFWAUSWELPCLLPIAHAUSWDFWIAHGCLLIAHWIAHELPWAUSSATMIAHCLLWELPIAHWIAHCLLWCLLAUSGIAHCLLGELPCLLCCLLELPBIAHSATBELPCLLWELPAUSCIAHAUSGELPSATDELPCLLMSATDFWWIAHAUSGIAHCLLCIAHELPCDFWELPWAUSCLLCAUSSATWAUSSATBELPCLLDIAHAUSPCLLSATWAUSIAHWAUSIAHWDFWIAHWSATAUSSDFWIAHMELPCLLMAUSELPDIAHELPWELPIAHDIAHCLLMAUSIAHP',
    # Day 7 -- 255 records
    'CLLSATPIAHDFWWCLLAUSBDFWELPWIAHCLLCIAHDFWWIAHCLLWCLLSATWIAHCLLWIAHDFWWDFWCLLWAUSDFWGELPSATDELPSATDAUSDFWMDFWELPWCLLAUSCSATELPWIAHCLLWSATDFWCDFWSATCAUSCLLWDFWCLLWCLLELPWSATIAHGDFWIAHMSATAUSWCLLIAHCCLLIAHWELPDFWWCLLSATMSATCLLWAUSCLLWAUSSATWSATELPCSATDFWSCLLDFWWSATAUSBDFWELPCDFWIAHWIAHCLLDIAHSATWCLLSATWDFWELPWSATCLLWCLLAUSGAUSSATCAUSDFWCDFWIAHWIAHDFWMSATDFWWELPIAHCELPIAHCDFWCLLWSATDFWWELPSATWIAHCLLCELPCLLWCLLIAHGELPSATWAUSCLLCSATCLLWDFWCLLWSATCLLMSATIAHWAUSIAHCSATDFWPSATAUSWAUSELPCSATIAHCIAHCLLWDFWSATWIAHAUSWCLLELPDSATCLLWELPDFWWSATIAHBSATIAHCAUSELPGSATAUSGSATAUSWSATAUSWELPDFWCDFWELPWELPCLLWDFWCLLWIAHCLLWCLLDFWWELPSATWIAHCLLCDFWAUSSDFWELPBDFWCLLBCLLIAHWCLLDFWMAUSELPGIAHDFWCDFWAUSWSATELPCIAHSATWCLLAUSDELPAUSWAUSSATWDFWCLLDIAHSATBDFWIAHCCLLDFWMSATDFWGIAHDFWWDFWELPCELPCLLWCLLIAHWIAHAUSWAUSELPWSATAUSCELPCLLCCLLDFWDAUSSATCSATCLLWCLLELPWDFWIAHWELPDFWCSATDFWGAUSCLLWELPSATDSATIAHMELPCLLWDFWAUSDSATIAHGDFWAUSCELPIAHCSATCLLWDFWCLLWAUSIAHWELPSATWELPAUSGELPSATSCLLIAHMDFWIAHPSATIAHWCLLIAHBAUSSATSELPAUSWELPSATWAUSSATMIAHELPMELPIAHSIAHELPWELPDFWCCLLIAHCSATAUSMDFWCLLMSATELPDELPCLLCAUSCLLWCLLIAHSCLLAUSCELPCLLGDFWSATMSATIAHDELPCLLGIAHSATCIAHDFWWAUSSATCIAHCLLWDFWSATGCLLSATWELPAUSWELPAUSCELPCLLPCLLSATWDFWCLLWCLLDFWGELPIAHDAUSELPCIAHSATWIAHAUSMELPCLLWELPCLLCSATIAHWSATELPMIAHCLLCAUSSATCSATCLLCSATAUSMIAHDFWDDFWSATWELPCLLWIAHCLLWSATIAHWELPDFWWDFWSATDDFWELPWSATELPGAUSCLLMSATELPDIAHSATCCLLDFWBDFWSATWIAHSATCDFWIAHMELPIAHWCLLDFWPIAHCLLWSATDFWWCLLDFWCDFWIAHWCLLELPBELPSATCDFWSATMDFWELPWCLLSATCDFWIAHCDFWCLLWCLLSATCDFWELPWSATCLLCCLLDFWCDFWAUSWELPDFWWSATDFWWELPIAHMSATIAHWIAHELPWAUSELPDCLLIAHWDFWIAHGDFWCLLWELPIAHWIAHAUSCCLLDFWCDFWSATWSATIAHCDFWIAHMIAHDFWWCLLDFWCAUSIAHGELPDFWMSATAUSBELPAUSPDFWAUSCSATCLLWIAHSATMAUSIAHWELPCLLMDFWSATCCLLIAHWCLLSATWSATAUSCELPCLLWAUSDFWPCLLSATCSATELPWAUSDFWWSATIAHW',
    # Day 8 -- 225 records
    'CLLDFWMCLLIAHWAUSCLLMSATELPMIAHAUSGCLLIAHCDFWCLLDSATIAHWSATIAHPCLLSATCELPCLLWSATDFWCAUSELPGIAHSATWELPDFWWAUSIAHWDFWAUSCCLLSATWAUSSATCAUSIAHMELPSATWAUSELPWSATIAHCAUSDFWWCLLELPCSATIAHWAUSCLLCELPSATCELPSATMCLLELPMDFWSATSDFWELPWCLLAUSWELPAUSWELPAUSCSATIAHWAUSELPWELPCLLWIAHELPWDFWAUSMSATDFWWELPIAHCDFWCLLCDFWSATMAUSIAHPDFWAUSWAUSCLLWELPCLLWELPCLLPIAHAUSDAUSIAHDCLLAUSGELPAUSMCLLSATCELPIAHCAUSSATPSATDFWCAUSIAHDDFWCLLCDFWAUSWELPSATSIAHCLLWAUSCLLWDFWELPGIAHSATMAUSELPBELPAUSWSATELPCELPDFWDAUSELPMDFWELPWCLLELPCSATELPWIAHDFWCIAHDFWWAUSDFWGDFWSATCAUSSATWCLLIAHGELPDFWWCLLAUSWAUSSATWELPIAHCSATELPMDFWSATBELPIAHCELPCLLWELPIAHDCLLAUSWDFWELPWIAHDFWMELPAUSMAUSDFWBSATCLLMELPAUSWIAHSATCELPIAHDSATIAHDDFWAUSWSATELPMSATIAHCIAHSATCSATCLLGIAHDFWWCLLELPWIAHAUSWELPSATMELPSATCAUSDFWWDFWELPCDFWELPMDFWIAHSCLLSATWELPSATWDFWCLLPCLLAUSWCLLELPWELPIAHCIAHCLLCELPAUSBIAHAUSGSATAUSWAUSDFWWAUSSATWIAHCLLWELPAUSWCLLELPWSATIAHCCLLDFWPSATIAHCIAHELPWCLLDFWWIAHCLLCSATDFWWIAHDFWMIAHSATCELPIAHGIAHSATWELPDFWMELPSATWDFWSATGCLLDFWPSATIAHDELPAUSWSATELPWIAHDFWWAUSSATDSATAUSGCLLAUSCCLLDFWCCLLSATDELPAUSWELPIAHPIAHAUSWAUSSATWAUSIAHWDFWSATDAUSIAHWELPAUSWAUSELPWELPAUSWDFWAUSCELPAUSGIAHSATCDFWIAHMCLLSATWCLLAUSWAUSSATWELPSATWIAHAUSMIAHSATSAUSIAHWDFWIAHWSATIAHCIAHSATWCLLAUSCAUSIAHWAUSELPWAUSELPCIAHCLLWAUSCLLCDFWIAHWELPDFWWCLLAUSWCLLELPCELPSATBAUSCLLMELPAUSWIAHCLLCCLLIAHGDFWSATBCLLSATMSATCLLDELPDFWWDFWIAHWCLLSATWAUSSATWELPDFWWIAHAUSCELPDFWBELPDFWWCLLIAHCIAHSATCCLLSATWSATCLLCCLLELPWDFWCLLMIAHELPWCLLDFWWCLLIAHBAUSELPPSATIAHCIAHELPBSATAUSWCLLSATGDFWSATMAUSSATBSATDFWWIAHSATMSATELPDCLLSATMIAHELPGCLLAUSWIAHDFWGELPCLLW',
    # Day 9 -- 137 records
    'IAHCLLCIAHAUSMIAHELPDDFWCLLMDFWELPCAUSELPMIAHCLLDIAHCLLWIAHSATWSATDFWWIAHCLLWSATELPGELPCLLBCLLDFWWSATCLLMCLLDFWMDFWELPBELPSATMSATAUSMIAHELPWDFWIAHCDFWCLLMCLLDFWMIAHELPPSATDFWMSATAUSCDFWCLLWSATAUSMSATDFWMDFWELPBCLLSATWAUSCLLMSATCLLWCLLSATPDFWSATWAUSDFWMDFWSATWDFWELPPDFWSATPSATELPPAUSSATMSATIAHMAUSSATMCLLIAHMIAHDFWWCLLDFWMSATCLLWAUSSATMIAHDFWMAUSCLLPDFWELPWSATAUSMSATCLLBAUSDFWMIAHCLLWIAHELPGDFWCLLMAUSCLLCELPIAHWDFWAUSBDFWSATWIAHSATCAUSCLLCIAHCLLCSATDFWWELPAUSGDFWELPDCLLDFWCAUSDFWCCLLSATBCLLIAHWCLLAUSWAUSDFWBAUSCLLWDFWIAHGDFWAUSMCLLSATMAUSIAHCIAHDFWWCLLELPWIAHELPSELPSATMIAHCLLGSATIAHMCLLIAHWCLLELPGELPIAHWAUSCLLWELPSATDIAHAUSBAUSDFWWELPIAHMDFWCLLCSATCLLGELPAUSMAUSELPMIAHCLLPAUSSATWSATIAHCELPCLLWCLLAUSMDFWIAHWAUSDFWPSATCLLMSATELPBSATDFWPAUSDFWPDFWELPGSATDFWCELPSATPELPDFWWIAHSATCIAHSATWIAHAUSDAUSCLLWCLLSATWSATIAHMELPAUSCCLLDFWMCLLIAHWELPCLLMELPSATCDFWCLLWAUSIAHBSATDFWBELPIAHMAUSCLLBCLLIAHMCLLSATMAUSSATWSATCLLWDFWAUSDELPIAHPAUSIAHCELPAUSMSATDFWWCLLDFWW',
    # Day 10 -- 70 records
    'IAHELPPAUSDFWPAUSSATMAUSDFWGDFWSATBDFWIAHMDFWIAHPELPSATWIAHCLLPIAHAUSMDFWIAHPCLLSATGIAHDFWWELPIAHMELPIAHCAUSCLLMCLLDFWMAUSIAHMDFWCLLDAUSSATBDFWCLLPELPSATMELPAUSDAUSELPPCLLSATMAUSCLLMAUSCLLPIAHCLLPDFWCLLPSATDFWPIAHAUSBELPSATPDFWCLLWIAHCLLWELPSATBAUSDFWCDFWELPBAUSSATCIAHCLLMELPCLLCSATDFWMCLLIAHMDFWCLLCAUSCLLMSATAUSBELPDFWWCLLSATWELPCLLBAUSIAHBAUSDFWPSATDFWMELPAUSWELPDFWWDFWIAHMIAHDFWMSATIAHMSATIAHMIAHSATCELPAUSBCLLSATBDFWELPMELPDFWGSATAUSWCLLELPDSATELPBCLLELPMDFWSATMCLLAUSBCLLDFWPIAHAUSW',
]

# Test Cases: 
# Most frequent: days = ['AUSJEKWAGKWIEWJAKWIEWAKSJDJD']
# Ranking: Weather (W): 3 Deicing (D): 1 Crew Timeout (C): 0 Mechanical (M): 0 
#   Ground Stop (G): 0 Gate Conflict (P): 0 
# For a tie: days = ['AUSJEKWAGKWIEDJAKWIEWAKSJDJD'] 
# Ranking: Weather (W): 2 Deicing (D): 2 Crew Timeout (C): 0 Mechanical (M): 0 
#   Ground Stop (G): 0 Gate Conflict (P): 0 
#   Connecting-Flight Backup (B): 0 Software/Scheduling System (S): 0
# For one 2/8: days = ['AUSJEKDAGKWIEDJAKWIEPAKSJDJP'] 
# Ranking: Deicing (D): 2 Gate Conflict (P): 2
#   Weather (W): 0 Crew Timeout (C): 0 Mechanical (M): 0 
#   Ground Stop (G): 0 Connecting-Flight Backup (B): 0 Software/Scheduling System (S): 0
# For two days: days = ['AUSJEKWAGKWIEDJAKWIEWAKSJDJD', 'AUSJEKWAGKWIEDJAKWIEWAKSJDJD']
#   Ranking: Weather (W): 4 Deicing (D): 4 Crew Timeout (C): 0 Mechanical (M): 0 
#   Ground Stop (G): 0 Gate Conflict (P): 0 

day_4_5 = "IAHAUSBCLLDFWWCLLIAHWCLLDFWGSATELPWCLLAUSMCLLIAHWCLLELPMCLLELPDELPIAHGAUSELPCCLLAUSC"
print(f"Length before: {len(days)}")
days.insert(4, day_4_5)

causes = []
counts = []
day_list = []

print(f"Length after addition: {len(days)}")
days.append(days[3])
print(f"Length after duplication: {len(days)}")

for day in days:
    temp_list = days[:]
    temp_list.remove(day)
    if day in temp_list:
        days.remove(day)
    for string_i in range(0, len(day), 7):
        day_list.append(day[string_i:string_i+7])

    
print(f"Length after deletion: {len(days)}")


for day in day_list:
    index = -1
    if day[-1] in causes:
        index = causes.index(day[-1])
    else:
        causes.append(day[-1])
        counts.append(0)
    counts[index] += 1


for i in range(1, len(counts)):
    current = counts[i]
    name = causes[i]
    j = i-1

    while j >= 0 and current > counts[j]:
        temp = causes[j+1]
        causes[j+1] = causes[j]
        causes[j] = temp
        
        temp = counts[j+1]
        counts[j+1] = counts[j]
        counts[j] = temp
                
        j -= 1

    causes[j+1] = name
    counts[j+1] = current

total = sum(counts)
print(f"Total records processed: {total}")

print("Disruption ranking (most to least frequent):")
num = 1; printed = [0 for _ in range(8)]
for cause in causes:
    match cause:
        case "W": print(f"{num}. Weather ", end = ""); printed[0] = 1
        case "C": print(f"{num}. Crew Timeout ", end = ""); printed[1] = 1
        case "M": print(f"{num}. Mechanical ", end = ""); printed[2] = 1
        case "G": print(f"{num}. Ground Stop ", end = ""); printed[3] = 1
        case "D": print(f"{num}. Deicing ", end = ""); printed[4] = 1
        case "P": print(f"{num}. Gate Conflict ", end = ""); printed[5] = 1
        case "B": print(f"{num}. Connecting-Flight Backup ", end = ""); printed[6] = 1
        case "S": print(f"{num}. Software/Scheduling System ", end = ""); printed[7] = 1
    print(f"({cause}): {counts[num-1]}")
    num += 1

weather_types = ["Weather (W)", "Crew Timeout (C)", "Mechanical (M)", "Ground Stop (G)", "Deicing (D)", "Gate Conflict (P)", 
                "Connecting-Flight Backup (B)", "Software/Scheduling System (S)"]
for i in range(8):
    if printed[i] == 0:
        print(f"{num}. {weather_types[i]}: 0")
        num += 1

def occurrence_rating(count):
    if count <= 5:
        return 2
    elif count <= 15:
        return 5
    elif count <= 30:
        return 7
    else:
        return 9

# RPN = Severity × Occurrence × Detection
risk_causes = ["W", "C", "M", "G", "D", "P", "B", "S"]
severity    = [6,   7,   8,   5,   4,   3,   5,   10]
detection   = [2,   4,   3,   2,   2,   3,   5,   9]
RPN_list = [0 for _ in range(len(counts))]

for i in range(len(counts)):
    SD_index = risk_causes.index(causes[i])
    occurrence = occurrence_rating(counts[i])
    RPN_list[SD_index] = severity[i]*occurrence*detection[i]


for i in range(1, len(RPN_list)):
    current = RPN_list[i]
    name = risk_causes[i]
    j = i-1

    while j >= 0 and current > RPN_list[j]:
        temp = risk_causes[j+1]
        risk_causes[j+1] = risk_causes[j]
        risk_causes[j] = temp
        
        temp = RPN_list[j+1]
        RPN_list[j+1] = RPN_list[j]
        RPN_list[j] = temp
                
        j -= 1

    risk_causes[j+1] = name
    RPN_list[j+1] = current

def cause_type(letter):
    match letter:
            case "W": return "Weather "
            case "C": return "Crew Timeout "
            case "M": return "Mechanical "
            case "G": return "Ground Stop "
            case "D": return "Deicing "
            case "P": return "Gate Conflict "
            case "B": return "Connecting-Flight Backup "
            case "S": return "Software/Scheduling System "

print(f"Risk ranking (highest RPN to lowest):")
num = 1; printed = [0 for _ in range(8)]
for risk in risk_causes:
    match risk:
        case "W": print(f"{num}. Weather ", end = ""); printed[0] = 1
        case "C": print(f"{num}. Crew Timeout ", end = ""); printed[1] = 1
        case "M": print(f"{num}. Mechanical ", end = ""); printed[2] = 1
        case "G": print(f"{num}. Ground Stop ", end = ""); printed[3] = 1
        case "D": print(f"{num}. Deicing ", end = ""); printed[4] = 1
        case "P": print(f"{num}. Gate Conflict ", end = ""); printed[5] = 1
        case "B": print(f"{num}. Connecting-Flight Backup ", end = ""); printed[6] = 1
        case "S": print(f"{num}. Software/Scheduling System ", end = ""); printed[7] = 1
    print(f"({risk}): RPN {RPN_list[num-1]}")
    num += 1

print(f"Frequency-ranked #1 (from L1): {cause_type(causes[0])}({causes[0]})")
print(f"Risk-ranked #1: {cause_type(risk_causes[0])}({risk_causes[0]})")
print(f"Top cause changed: ", end = "")
if not(causes[0] == risk_causes[0]):
    print("YES")
else:
    print("NO")